GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NTYxNDMzZWEyZmVjNWNmYTRmNWRmZjQiLCJpYXQiOjE3MDEwMzA3OTMsImV4cCI6MTcwMTAzNDM5M30.5uy_JVu1Hbzdlrgydg8HaWU6CcVYzUP6YfnGzXSCGbk

{
  "author": "Lorem Ipsum Lorem Ipsum",
  "title": "Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet",
  "url": "https://www.lipsum.com/feed/html"
}

###
PUT http://localhost:3000/api/blogs/6562ceff30deae7625c8b484
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NTYxNDMzZWEyZmVjNWNmYTRmNWRmZjQiLCJpYXQiOjE3MDEwMzA3OTMsImV4cCI6MTcwMTAzNDM5M30.5uy_JVu1Hbzdlrgydg8HaWU6CcVYzUP6YfnGzXSCGbk

{
  "author": "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum",
  "title": "Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet",
  "url": "https://www.lipsum.com/feed/html"
}

###
DELETE http://localhost:3000/api/blogs/6562ceff30deae7625c8b484
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NTYxNDMzZWEyZmVjNWNmYTRmNWRmZjQiLCJpYXQiOjE3MDEwMzA3OTMsImV4cCI6MTcwMTAzNDM5M30.5uy_JVu1Hbzdlrgydg8HaWU6CcVYzUP6YfnGzXSCGbk
