name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./server
jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint && cd ../client && npm i && npm run lint
      - name: build
        run: npm run build:ui
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
          file_name: .env
          directory: server
          fail_on_empty: false
          sort_keys: false
      - name: test
        run:  npm run test --verbose --maxWorkers=2 --runInBand
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }} && ${{ github.event_name == 'push' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run:
          curl "$deploy_url"